[package]
name = "graph"
version = "0.1.0"
authors = ["Mikhail Modin <mikhailm1@gmail.com>"]
edition = "2018"

[dependencies]
svg = "0.9"
pest = "2.1"
pest_derive =  "2.1"
rand = "0.8"
log = "0.4"
getrandom  = { version = "0.2.2", features = ["js"] }

[dev-dependencies]
simplelog = "0.11"
